### ISSUE TITLE
Passenger Apache conf failing

### ISSUE THREAD

**Issue by mvl22** [cyclestreets/cyclescape-chef#30]
```* service[apache2] action restartapache2: Syntax error on line 123 of /etc/apache2/apache2.conf: Syntax error on line 1 of /etc/apache2/mods-enabled/passenger.load: Cannot load /var/lib/gems/1.9.1/gems/passenger-4.0.53/buildout/apache2/mod_passenger.so into server: /var/lib/gems/1.9.1/gems/passenger-4.0.53/buildout/apache2/mod_passenger.so: cannot open shared object file: No such file or directory```

On the latest fallback VM I'm installing Cyclescape on is no file at:
```
/var/lib/gems/1.9.1/gems/passenger-4.0.53/buildout/apache2/mod_passenger.so
```
but there is one at:
```
/var/lib/gems/2.1.0/gems/passenger-4.0.53/buildout/apache2/mod_passenger.so
```

**Comment by mvl22** [comment]
A couple of references in the code:
https://github.com/cyclestreets/cyclescape-chef/search?q=passenger.load

**Comment by mvl22** [comment]
Doesn't look like it's being interpolated correctly:

```/etc/apache2/mods-available/passenger.load``` ends up containing:

```
LoadModule passenger_module /var/lib/gems/<= @gem_folder =>/gems/passenger-/buildout/apache2/mod_passenger.so
<IfModule mod_passenger.c>
  PassengerRoot /var/lib/gems/<= @gem_folder =>/gems/passenger-
  PassengerDefaultRuby /usr/bin/ruby<= @ruby_version =>
</IfModule>
```

**Comment by nikolai-b** [comment]
Sorry, that commit message wasn't meant to close the issue (I was rushed on the train).  I've pushed again, can you let me know if that is any better? (I need to read more chef...)

**Comment by mvl22** [comment]
```
LoadModule passenger_module /var/lib/gems/<= @gem_folder =>/gems/passenger-/buildout/apache2/mod_passenger.so
<IfModule mod_passenger.c>
  PassengerRoot /var/lib/gems/<= @gem_folder %>/gems/passenger-
  PassengerDefaultRuby /usr/bin/ruby<= @ruby_version %>
</IfModule>
```

is what results still, I'm afraid.

(Note that the first line in the above wasn't changed in the same way - but clearly the interpolation generally is still wrong.)

**Comment by mvl22** [comment]
Latest commit results in:

```
LoadModule passenger_module /var/lib/gems//gems/passenger-/buildout/apache2/mod_passenger.so
<IfModule mod_passenger.c>
  PassengerRoot /var/lib/gems//gems/passenger-
  PassengerDefaultRuby /usr/bin/ruby2.1
</IfModule>
```

so looks like the ruby_version variable is correct but not the gem_folder one.

**Comment by nikolai-b** [comment]
Sorry this is a bit late for me and I need to get to sleep.  I really need
a chance to read some chef but I hope the last commit sorts it, I got the
specs to run and now they pass.
If it doesn't work do you want to try hard coding the values?

**Comment by mvl22** [comment]
Yep, that seems to be good now! I'll try it out fully but it seems to have completed.

Get good sleep :)

**Comment by mvl22** [comment]
Yep, all good.
